### ISSUE TITLE
standalone app docs is not the right link

### ISSUE THREAD

**Issue by LFGaming** [berty/weshnet-expo-examples#5]
In [./examples/hello-wesh](https://github.com/berty/weshnet-expo-examples/blob/main/examples/hello-wesh/README.md) step 4, it says:
> Since native modules doesn't work on the Expo Go, you need to run the app as a [standalone app](https://docs.expo.dev/workflow/run-on-device/#running-a-project-as-a-standalone-app):

The link to the standalone app docs does not work.
Was [this ](https://docs.expo.dev/modules/use-standalone-expo-module-in-your-project/) the site that was meant?

**Comment by iuricmp** [comment]
Hi @LFGaming , 
You are correct! Could you please open a little PR?
Thank you!

**Comment by LFGaming** [comment]
Hi @iuricmp,
Here is the fix :)
